name: Backtest

on:
  workflow_dispatch:
    inputs:
        tickers:
        description: 'Comma-separated list of tickers'
        required: false
             default: 'AAPL,MSFT,GOOGL'
               art_date:
             description: 'Start date (YYYY-MM-DD)'
             required: false
             default: '2024-01-01'
               d_date:
             description: 'End date (YYYY-MM-DD)'
             required: false
             default: '2025-01-01'

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
           - uses: actions/checkout@v4
     
    
           - name: Set up Python
             uses: actions/setup-python@v5
     
             with:
               python-version: '3.10'

           - name: Install dependencies
             run: |
               pip install --no-cache-dir -r requirements.txt

           - name: Run backtest
             run: |
          python - << 'PY'
          import os
          from trading_strategy_app.trading_strategy_app import historical_backtest

          tickers = os.getenv('INPUT_TICKERS', 'AAPL,MSFT,GOOGL').split(',')
          start = os.getenv('INPUT_START_DATE', '2024-01-01')
          end = os.getenv('INPUT_END_DATE', '2025-01-01')

          historical_backtest(tickers, start, end)
          PY
     
      - name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: backtest_results
                    path: backtest_results.csv
# trigger
