# Triggered to refresh indentation
name: Backtest

on:
  workflow_dispatch:
    inputs:
      tickers:
        description: 'comma‑separated list of tickers'
        required: false
        default: 'AAPL,MSFT,GOOGL'
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        default: '2024-01-01'
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        default: '2025-01-01'

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backtest
        run: |
          python trading_strategy_app/backtest.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backtest_results
          path: backtest_results.csv